import 'package:flutter/foundation.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class SubtitleEntry {
  final String text;
  final Duration offset;
  final Duration duration;
  final List<SubtitlePart> parts;

  SubtitleEntry({
    required this.text,
    required this.offset,
    required this.duration,
    this.parts = const [],
  });

  Duration get end => offset + duration;
}

class SubtitlePart {
  final String text;
  final Duration offset; // caption内の相対オフセット

  SubtitlePart({required this.text, required this.offset});
}

class SubtitleTrackInfo {
  final String languageCode;
  final String languageName;
  final bool isAutoGenerated;

  SubtitleTrackInfo({
    required this.languageCode,
    required this.languageName,
    required this.isAutoGenerated,
  });
}

class SubtitleService {
  /// 利用可能な字幕トラック一覧を取得
  static Future<List<SubtitleTrackInfo>> getAvailableTracks(
      String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest =
          await yt.videos.closedCaptions.getManifest(videoId);
      return manifest.tracks
          .map((t) => SubtitleTrackInfo(
                languageCode: t.language.code,
                languageName: t.language.name,
                isAutoGenerated: t.isAutoGenerated,
              ))
          .toList();
    } catch (_) {
      return [];
    } finally {
      yt.close();
    }
  }

  /// 字幕データを取得（優先順位: 指定言語 → 日本語 → 英語 → 最初のトラック）
  static Future<List<SubtitleEntry>?> fetchSubtitles(
    String videoId, {
    String? preferredLanguage,
  }) async {
    final yt = YoutubeExplode();
    try {
      debugPrint('[SubtitleService] getManifest開始: $videoId');
      final manifest =
          await yt.videos.closedCaptions.getManifest(videoId);
      debugPrint('[SubtitleService] トラック数: ${manifest.tracks.length}');
      for (final t in manifest.tracks) {
        debugPrint('[SubtitleService]   ${t.language.code} (${t.language.name}) auto=${t.isAutoGenerated}');
      }
      if (manifest.tracks.isEmpty) return null;

      // トラック選択
      ClosedCaptionTrackInfo? trackInfo;

      // 優先言語
      if (preferredLanguage != null) {
        trackInfo = _findTrack(manifest, preferredLanguage);
      }
      // 日本語
      trackInfo ??= _findTrack(manifest, 'ja');
      // 英語
      trackInfo ??= _findTrack(manifest, 'en');
      // 最初のトラック
      trackInfo ??= manifest.tracks.first;

      debugPrint('[SubtitleService] 選択: ${trackInfo.language.code}');
      final track = await yt.videos.closedCaptions.get(trackInfo);
      debugPrint('[SubtitleService] 字幕数: ${track.captions.length}');
      return track.captions
          .map((c) => SubtitleEntry(
                text: c.text,
                offset: c.offset,
                duration: c.duration,
                parts: c.parts
                    .map((p) => SubtitlePart(
                          text: p.text,
                          offset: p.offset,
                        ))
                    .toList(),
              ))
          .toList();
    } catch (e, st) {
      debugPrint('[SubtitleService] エラー: $e');
      debugPrint('[SubtitleService] $st');
      return null;
    } finally {
      yt.close();
    }
  }

  static ClosedCaptionTrackInfo? _findTrack(
      ClosedCaptionManifest manifest, String lang) {
    // 手動字幕を優先
    final manual = manifest.tracks.where(
        (t) => t.language.code == lang && !t.isAutoGenerated);
    if (manual.isNotEmpty) return manual.first;
    // 自動生成
    final auto = manifest.tracks
        .where((t) => t.language.code == lang && t.isAutoGenerated);
    if (auto.isNotEmpty) return auto.first;
    return null;
  }
}
